FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
RUN chmod +x mvnw

# Устанавливаем родительский POM
RUN ./mvnw clean install -N -DskipTests

# Устанавливаем common
COPY common common
RUN ./mvnw -f common/pom.xml clean install -DskipTests

# Собираем api-gateway
COPY api-gateway api-gateway
RUN ./mvnw -f api-gateway/pom.xml clean package -DskipTests

# Ищем JAR для api-gateway
RUN cp /app/api-gateway/target/api-gateway-*.jar /app/app.jar

FROM eclipse-temurin:21-jre-alpine
COPY --from=build /app/api-gateway/target/*.jar /app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app.jar"]